### ISSUE TITLE
[Vulnerability] interoperation between Java/Kotlin code and the WebAssembly task

### ISSUE THREAD

**Issue by samkirton** [jasonwyatt/KWasm#151]
Hi,

Surely your goal to `support interoperation between Java/Kotlin code and the WebAssembly it is tasked with running.`, conflicts with `maintain WebAssembly's strict sandbox-like functionality`?

**Comment by jasonwyatt** [comment]
It does not, since all interop has to be explicitly declared in both the
actual WASM as well as in the JVM side of things.

**Comment by jasonwyatt** [comment]
For more detail: WASM programs need to declare that they import a function/memory/table/global as a matter of course, and the host environment (JVM/Browser/Whatever) supplies those imports.
